// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsbelbevnokakjkqjnes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzYmVsYmV2bm9rYWtqa3FqbmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDU2NDAsImV4cCI6MjA2MjgyMTY0MH0.-i8zRaDAqJv0hW0W3yE-Pe0eJYDDN0JTiG97zTG6UWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);